/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _taurus_db_stateRow {
  'schemaVersion': number|bigint;
}
export interface cardRow {
  'cardId': any;
  'numOwned': number|bigint;
}
export interface individualRow {
  'cardId': any;
  'finish': any;
  'id'?: number|bigint;
  'location': any;
  'notes': any;
}
